version: '3.6'

services:
  php:
    build:
      context: .
      dockerfile: docker/images/php/Dockerfile
      target: dev
    container_name: ${PROJECT_PREFIX}_php
    hostname: ${PROJECT_PREFIX}_php
    working_dir: /app/code
    env_file:
        - .env
    volumes:
      - ./:/app
      - ./docker/config/dev/ssh:/root/.ssh/
      - ./docker/config/dev/git/.gitconfig:/root/.gitconfig
      - ./code/:/var/www/html
  web:
    image: nginx:alpine
    container_name: ${PROJECT_PREFIX}_web
    working_dir: /var/www/html
    volumes:
      - ./code/:/var/www/html
      - ./docker/config/dev/nginx:/etc/nginx/conf.d/
    ports:
      - ${WEB_PORT}:80
  db:
    image: mariadb:10.5
    container_name: ${PROJECT_PREFIX}_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my_vocabulary_api
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/config/dev/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/config/dev/mysql/init.sql.template:/docker-entrypoint-initdb.d/init.sql.template
  phpmyadmin:
    image: phpmyadmin
    container_name: ${PROJECT_PREFIX}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
volumes:
  dbdata:
